// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_b73kI7XsplnyBgHRWNzxoy5ObrJHF8U',
    appId: '1:1096291702596:android:f975acbf156bb789986911',
    messagingSenderId: '1096291702596',
    projectId: 'coffeeapp-35581',
    storageBucket: 'coffeeapp-35581.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2qgrKeGmRWL007EasK6hXblxXOYUCHVo',
    appId: '1:1096291702596:ios:64dbdbc9648b9546986911',
    messagingSenderId: '1096291702596',
    projectId: 'coffeeapp-35581',
    storageBucket: 'coffeeapp-35581.appspot.com',
    iosBundleId: 'com.example.coffeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2qgrKeGmRWL007EasK6hXblxXOYUCHVo',
    appId: '1:1096291702596:ios:64dbdbc9648b9546986911',
    messagingSenderId: '1096291702596',
    projectId: 'coffeeapp-35581',
    storageBucket: 'coffeeapp-35581.appspot.com',
    iosBundleId: 'com.example.coffeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmTLBOxZ1BMI6vAm5f7bXr2I0PBOEcjf4',
    appId: '1:1096291702596:web:a72e3ee3778050ae986911',
    messagingSenderId: '1096291702596',
    projectId: 'coffeeapp-35581',
    authDomain: 'coffeeapp-35581.firebaseapp.com',
    storageBucket: 'coffeeapp-35581.appspot.com',
  );
}
